version: '3.9'

services:
  revanced:
    build:
      context: .
      dockerfile: Dockerfile
    image: revanced-builder
    container_name: revanced-builder
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - .:/app:z
